CREATE DATABASE IF NOT EXISTS image_db;

USE image_db;

CREATE TABLE IF NOT EXISTS predictions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    prediction VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE USER IF NOT EXISTS 'grafana'@'%' IDENTIFIED BY 'grafana';
GRANT ALL PRIVILEGES ON image_db.* TO 'grafana'@'%';
FLUSH PRIVILEGES;
